# Archivo de propiedades de traducción al español.
# Colaboradores: lxuser

REMOVED_WORLD_SELECTION=Has eliminado tu selección de mundo. Trabajando con el mundo actual (si es posible).
CREATED_GROUP=Has creado un grupo llamado %s
DELETED_GROUP=Has eliminado un grupo llamado %s, ahora sus usuarios tienen el grupo por defecto.

ERROR_GROUP_ALREADY_EXISTS=¡El grupo '%s' ya existe\!
ERROR_GROUP_DOES_NOT_EXIST=¡El grupo '%s' no existe\!
ERROR_GG_DO_NOT_SUPPORT_INHERITANCE=GlobalGroups NO admite herencia.
ERROR_GG_DO_NOT_SUPPORT_INFO_NODES=GlobalGroups NO admite nodos de información.
ERROR_GROUP_NOT_INHERIT=El grupo %s no hereda de %s.
ERROR_GROUP_NOT_INHERIT_DIRECT=El grupo %s no hereda directamente de %s.
ERROR_GROUP_ALREADY_INHERITS=El grupo %s ya hereda de %s (puede que no directamente).

GROUP_NOW_INHERITS=El grupo %s ahora está en la lista de herencia de %s.
GROUP_REMOVED_INHERITANCE=El grupo %s fue eliminado de la lista de herencia de %s.

ERROR_USER_NO_ACCESS_PERMISSION=El usuario no tiene acceso a ese permiso.
ERROR_USER_NO_ACCESS_PERMISSION_DIRECT=El usuario no tiene acceso directo a ese permiso.
ERROR_GROUP_NO_ACCESS_PERMISSION=El grupo no tiene acceso a ese permiso.
ERROR_GROUP_NO_ACCESS_PERMISSION_DIRECT=El grupo no tiene acceso directo a ese permiso.
ERROR_GROUP_NO_ACCESS_VARIABLE=¡El grupo no tiene acceso a esa variable\!
ERROR_GROUP_NO_ACCESS_VARIABLE_DIRECT=¡El grupo no tiene acceso directo a esa variable\!
ERROR_USER_NO_ACCESS_VARIABLE=¡El usuario no tiene acceso a esa variable\!
ERROR_USER_NO_ACCESS_VARIABLE_DIRECT=¡El usuario no tiene acceso directo a esa variable\!

VARIABLE_REMOVED_FROM_USER=Variable %s eliminada del usuario %s.
VARIABLE_REMOVED_FROM_GROUP=Variable %s eliminada del grupo %s.
VARIABLE_ADDED_TO_USER=Variable %s: '%s' añadida al usuario %s.
VARIABLE_ADDED_TO_GROUP=Variable %s: '%s' añadida al grupo %s.
VARIABLE_VALUE=El valor de la variable '%s' es: '%s'.
VARIABLE_INHERITED=y el valor fue heredado del grupo:
VARIABLES_OF_GROUP=Variables del grupo %s:
VARIABLES_OF_USER=Variables del usuario %s:
VARIABLES_ALL_GROUPS=Más todas las variables de los grupos: %s

SUBGROUP_ADDED_USER=Has añadido el subgrupo '%s' al jugador '%s'.
SUBGROUP_ADDED_USER_TIMED=Has añadido el subgrupo '%s' al jugador '%s' con una duración de %d minutos.
SUBGROUP_REMOVED_USER=Has eliminado el subgrupo '%s' del jugador '%s'.
ERROR_SUBGROUP_ALREADY_AVAILABLE=El subgrupo '%s' ya está disponible para '%s'.
AND_ALL_PERMISSIONS_GROUPS=Y todos los permisos de los grupos: %s
AND_ALL_PERMISSIONS_SUBGROUPS=Y todos los permisos de los subgrupos: %s
GROUP_HAS_PERMISSIONS=El grupo '%s' tiene los siguientes permisos: %s
USER_HAS_PERMISSIONS=El jugador '%s' tiene los siguientes permisos: %s
GROUP_NO_SPECIFIC_PERMISSIONS=El grupo '%s' no tiene permisos directos.
USER_NO_SPECIFIC_PERMISSIONS=El jugador '%s' no tiene permisos directos.
ERROR_SAME_PERMISSIONS_OR_HIGHER=No puedes modificar a un jugador con los mismos permisos que tú, o superiores
ERROR_SAME_GROUP_OR_HIGHER=No puedes modificar a un jugador con el mismo grupo que tú, o superior.
ERROR_DIFFERENT_INHERITANCE_LINES=No puedes modificar a un jugador usando grupos con diferentes líneas de herencia.
ERROR_DESTINATION_HIGHER_THAN_YOURS=El grupo de destino no puede ser igual que el tuyo, ni superior.
ERROR_SUBGROUP_HIGHER_THAN_YOURS=El subgrupo no puede ser igual que el tuyo, ni superior.
ERROR_NEW_GROUP_NOT_HIGHER=El nuevo grupo debe tener un rango superior al actual.
ERROR_NEW_GROUP_NOT_LOWER=El nuevo grupo debe tener un rango inferior al actual.
ERROR_PLAYERS_NOT_MEMBERS_OF_GG=Los jugadores no pueden ser miembros de GlobalGroups directamente.
ERROR_YOU_DO_NOT_INHERIT=No puedes modificar a un jugador involucrando un grupo que tú no heredas.
ERROR_CANT_REMOVE_PERMISSION=No puedes eliminar un permiso que no tienes: '%s'
ERROR_CANT_ADD_PERMISSION=No puedes añadir un permiso que no tienes: '%s'

ERROR_BUKKIT_INVALID_ARGUMENTS=¡Bukkit proporcionó un array de argumentos inválido\! Cmd: %s args.length: %d
ERROR_UNABLE_TO_SAVE=No es posible guardar a menos que ejecutes '/mansave force'

WORLDS_AVAILABLE=Mundos disponibles:
YOU_HAVE_SELECTED_WORLD=Has seleccionado el mundo '%s'.
NO_WORLD_AVAILABLE=No hay un mundo seleccionado, y ahora no hay ningún mundo disponible.
NO_WORLD_SELECTED=No tienes ningún mundo seleccionado.
USING_WORLD=Trabajando con el mundo en el que está tu jugador.
USING_PERMISSIONS_OF_WORLD=Tu mundo ahora usa los permisos del mundo llamado: '%s'
NEGATED=\ (Negado)
SUPER_PERMS_REPORTS=SuperPerms informa el nodo:
USER_HAS_EXCEPTION_DIRECT=El usuario tiene directamente un nodo de excepción para ese permiso.
USER_HAS_NEGATION_DIRECT=El usuario tiene directamente un nodo de negación para ese permiso.
USER_HAS_PERMISSION_DIRECT=El usuario tiene directamente este permiso.
USER_HAS_VARIABLE_DIRECT=El usuario tiene directamente esta variable.
USER_INHERITS_EXCEPTION_FROM_GROUP=El usuario hereda un permiso de excepción del grupo:
USER_INHERITS_NEGATION_FROM_GROUP=El usuario hereda una negación de permiso del grupo:
USER_INHERITS_PERMISSION_FROM_GROUP=El usuario hereda el permiso del grupo:
GROUP_INHERITS_NEGATION_FROM_GROUP=El grupo hereda una negación de permiso del grupo:
GROUP_INHERITS_EXCEPTION_FROM_GROUP=El grupo hereda un permiso de excepción del grupo:
GROUP_INHERITS_PERMISSION_FROM_GROUP=El grupo hereda el permiso del grupo:
ERROR_REVIEW_ARGUMENTS=¡Revisa la cantidad de argumentos\!
USER_CHANGED_TO_DEFAULT=Has cambiado al jugador '%s' a la configuración por defecto.
USER_CHANGED_TO_GROUP=Has cambiado al jugador '%s' al grupo '%s' en el mundo '%s'.
REMOVED_PERMISSION_FROM_PLAYER=Has eliminado '%s' de los permisos del jugador '%s'.
REMOVED_ALL_PERMISSIONS_PLAYER=Has eliminado todos los permisos del jugador: %s
REMOVED_ALL_PERMISSIONS_GROUP=Has eliminado todos los permisos del grupo: %s
REMOVED_PERMISSION_FROM_GROUP=Has eliminado '%s' de los permisos del grupo '%s'.
ADDED_PERMISSION_TO_GROUP=Has añadido '%s' a los permisos del grupo '%s'.
ADDED_PERMISSION_TO_GROUP_TIMED=Has añadido '%s' a los permisos del grupo '%s' con una duración de %d minutos.
ADDED_PERMISSION_TO_USER=Has añadido '%s' a los permisos del usuario '%s'.
ADDED_PERMISSION_TO_USER_TIMED=Has añadido '%s' a los permisos del usuario '%s' con una duración de %d minutos.
ERROR_NO_MATCHING_PERMISSION_NODE=Ese nodo de permiso no coincide con ningún nodo.
ERROR_INVALID_DURATION=Duración inválida introducida con '%s'
PERMISSION_NODE=Nodo de permiso: %s
POSSIBLE_MATCH=Pero podría coincidir con el nodo: %s
RELOAD_REQUEST_ATTEMPT=Se intentó la solicitud para recargar el mundo '%s'.
RELOADED=¡Todos los ajustes y mundos fueron recargados\!

AUTOSAVE_ENABLE=¡El guardado automático está activado\!
AUTOSAVE_DISABLE=¡El guardado automático está desactivado\! Los permisos y subgrupos temporales no caducarán mientras el guardado esté desactivado\!
VALIDATE_STATUS=Validar si un jugador está en línea, ahora establecido en:
VALIDATE_1=A partir de ahora puedes editar jugadores desconectados... PERO:
VALIDATE_2=La manera correcta es escribir el nombre de usuario completo.

# ManWhois text elements.
NAME=Nombre:
GROUP=Grupo:
SUBGROUPS=Subgrupos:
OVERLOADED=Sobrecargado:
ORIGINAL_GROUP=Grupo original:

# ManCheckW text elements
WORLD_USING_DATA_FILES=Este mundo está usando los siguientes archivos de datos...
GROUPS=Grupos:
USERS=Usuarios:

# ListGroups text elements.
GROUPS_AVAILABLE=Grupos disponibles:
GG_AVALIABLE=GlobalGroups disponibles:

# Temp Commands text elements.
PLAYER_OVERLOADED=¡Jugador puesto en modo de sobrecarga\!
OVERLOAD_DISABLED=El modo de sobrecarga del jugador ahora está desactivado.
NO_OVERLOAD=No hay usuarios en modo de sobrecarga.
EMPTY_OVERLOAD=Todos los usuarios en modo de sobrecarga han vuelto a la normalidad.
OVERLOADED_USERS=Hay %d usuarios en modo de sobrecarga:

# BaseCommand text elements.
COMMAND_BLOCKS=Los comandos de GM no pueden ser llamados desde bloques de comandos, a menos que 'allow_commandblocks' sea 'true'.
LOCATION=Ubicación:
COMMAND_ERROR=Todos los comandos están bloqueados debido a un error. Revisa /plugins/groupmanager/error.log o la consola y luego intenta ejecutar '/manload'.
COMMAND_NOT_PERMITTED=No tienes permiso para usar ese comando.
DEFAULT_WORLD_SELECTED=No se pudo recuperar tu mundo. Se seleccionó el mundo por defecto '%s'.
WORLD_SELECTION_NEEDED=No se pudo recuperar tu mundo. Se requiere selección de mundo.
USE_MANSELECT=Usa /manselect <world>
PLAYER_NOT_FOUND=¡Jugador no encontrado\!
TOO_MANY_MATCHES=¡Se encontraron demasiadas coincidencias\!

# Notify text elements.
PLAYER_WAS=\ fue
YOU_WERE=Fuiste
MOVED_TO_GROUP=\ movido al grupo %s en el mundo %s.

# WorldDataHolder
WorldDatHolder.ERROR_NO_GROUPS_FILE=¡El archivo que debería contener los grupos no existe\!
WorldDatHolder.ERROR_ACCESSING_GROUPS_FILE=¡Error al acceder al archivo de grupos\!
WorldDatHolder.ERROR_NO_USERS_FILE=¡El archivo que debería contener los usuarios no existe\!
WorldDatHolder.ERROR_ACCESSING_USERS_FILE=¡Error al acceder al archivo de usuarios\!
WorldDatHolder.ERROR_INVALID_FILE=Tu archivo %s es inválido. Mira la consola para más detalles.
WorldDatHolder.ERROR_NO_GROUPS=No tienes grupos en %s
WorldDatHolder.ERROR_INVALID_GROUP_NAME=Nombre de grupo inválido para la entrada de grupo '%s' en el archivo: %s
WorldDatHolder.ERROR_INVALID_CHILD_NODE=Nodos hijos inválidos para el grupo '%s' en el archivo: %s
WorldDatHolder.ERROR_GROUP_DUPLICATE=Este grupo fue declarado más de una vez: %s en el archivo: %s
WorldDatHolder.ERROR_INVALID_FORMAT=Formato inválido encontrado en '%s' para el grupo: %s en el archivo: %s
WorldDatHolder.ERROR_DEFAULT_DUPLICATE=El grupo '%s' afirma ser por defecto donde '%s' ya lo era.
WorldDatHolder.WARN_OVERIDE_DEFAULT=Sobrescribiendo la primera solicitud de por defecto en el archivo: %s
WorldDatHolder.ERROR_UNKNOWN_TYPE=Tipo desconocido de nodo '%s' (debería ser String o List<String>) para el grupo: %s en el archivo: %s
WorldDatHolder.ERROR_UNKNOWN_ENTRY=Entrada desconocida encontrada en '%s' para el grupo: %s en el archivo: %s
WorldDatHolder.WARN_GROUP_NO_INFO=¡El grupo '%s' no tiene sección 'info'\!
WorldDatHolder.WARN_USING_DEFAULT=Usando valores por defecto:
WorldDatHolder.ERROR_NO_DEFAULT=No se declaró un Grupo por Defecto en el archivo: %s
WorldDatHolder.WARN_INHERITED_NOT_FOUND=Grupo heredado '%s' no encontrado para el grupo %s. Ignorando entrada en el archivo: %s
WorldDatHolder.ERROR_INVALID_NODE_USER=Nodo inválido para la entrada de usuario #(%d) en el archivo: %s
WorldDatHolder.ERROR_INVALID_FORMAT_FOR_USER=Formato inválido encontrado para el usuario: %s en el archivo: %s
WorldDatHolder.ERROR_DUPLICATE_USER=Este usuario fue declarado más de una vez: %s en el archivo: %s
WorldDatHolder.ERROR_INVALID_FORMAT_IN_USER=Formato inválido encontrado en '%s' para el usuario: %s en el archivo: %s
WorldDatHolder.ERROR_UNKNOWN_ENTRY_USER=Entrada desconocida encontrada en '%s' para el usuario: %s en el archivo: %s
WorldDatHolder.WARN_NO_GROUP_STATED=No existe el grupo %s, como se indicó para el jugador %s: Establecido a '%s' para el archivo: %s
WorldDatHolder.WARN_INVALID_SUBGROUP=Datos de Subgrupo inválidos para el usuario: %s. Ignorando entrada en el archivo: %s
WorldDatHolder.WARN_SUBGROUP_NOT_FOUND=Subgrupo '%s' no encontrado para el usuario: %s. Ignorando entrada en el archivo: %s
WorldDatHolder.WARN_NO_DEFAULT_GROUP=No hay grupo por defecto para el mundo:

# WorldsHolder
WorldsHolder.ADDING_GROUPS_MIRROR=Añadiendo espejo de grupos para %s.
WorldsHolder.ADDING_USERS_MIRROR=Añadiendo espejo de usuarios para %s
WorldsHolder.ATTEMPT_TO_LOAD=Intentando cargar el mundo %s...
WorldsHolder.CHECKING_DATA=Comprobando datos para %s.
WorldsHolder.CREATING_FOLDERS=Creando carpetas para %s.
WorldsHolder.ERROR_NO_DEFAULT_GROUP=¡No hay grupo por defecto\!
WorldsHolder.ERROR_NO_GROUPS_FILE=El archivo de grupos para el mundo '%s' no existe: %s
WorldsHolder.ERROR_NO_USERS_FILE=El archivo de usuarios para el mundo '%s' no existe: %s
WorldsHolder.MIRRORING_ERROR=Error de espejado con %s. ¡Bucle recursivo detectado\!
WorldsHolder.NEWER_GROUPS_FILE_LOADING=Se encontró un archivo de Grupos más reciente (Cargando cambios)\!
WorldsHolder.NEWER_USERS_FILE_LOADING=Se encontró un archivo de Usuarios más reciente (Cargando cambios)\!
WorldsHolder.NO_DATA=No hay datos para %s.
WorldsHolder.UNKNOWN_MIRRORING_FORMAT=Formato de espejado desconocido para %s
WorldsHolder.WARN_NEWER_GROUPS_FILE_UNABLE=Se encontró un archivo de Grupos más reciente para %s, pero tenemos cambios locales\!
WorldsHolder.WARN_NEWER_USERS_FILE_UNABLE=Se encontró un archivo de Usuarios más reciente para %s, pero tenemos cambios locales\!
WorldsHolder.WHAT_HAPPENED=¿QUÉ HA PASADO?
WorldsHolder.WORLD_FOUND=Mundo encontrado: %s
WorldsHolder.WORLD_LOAD_SUCCESS=Carga exitosa del mundo %s...
WorldsHolder.WORLD_NOT_FOUND_DEFAULT=El mundo solicitado %s no se encontró o está mal espejado. Devolviendo el mundo por defecto...
WorldsHolder.WORLD_NOT_FOUND_UNNAMED=El mundo solicitado %s no se encontró o está mal espejado. Devolviendo all_unnamed_worlds...

# GlobalGroups Text
GlobalGroups.BAD_FORMATTED=El GlobalGroup '%s' está formateado incorrectamente.
GlobalGroups.ERROR_NEWER_GG_FOUND=¡Se encontró un archivo de GlobalGroups más reciente, pero tenemos cambios locales\!
GlobalGroups.INVALID_GROUP_NAME=Nombre de grupo inválido para la entrada de GlobalGroup \#[%d] en el archivo: %s
GlobalGroups.INVALID_PERMISSION_NODE=Nodo de permiso inválido en el grupo global: %s
GlobalGroups.UNKNOWN_PERMISSION_TYPE=Tipo de nodo de permiso desconocido en el grupo global: %s
GlobalGroups.WARN_NEWER_GG_FOUND_LOADING=¡Se encontró un archivo de GlobalGroups más reciente (Cargando cambios)\!

# Config text.
GMConfiguration.CORRUPT_NODE=Falta o está corrupto el nodo '%s'. Usando ajustes por defecto
GMConfiguration.ERROR_CREATING_CONFIG=Error al crear un nuevo config.yml
GMConfiguration.ERRORS_IN_CONFIG=Hay errores en tu config.yml. Usando ajustes por defecto
GMConfiguration.MISSING_NODE=El config.yml no tiene '%s'.

GroupManager.BACKUPS_RETAINED_MSG=¡Las copias de seguridad se conservarán durante %d horas\!
GroupManager.CANT_ENABLE=¡No se puede habilitar %s versión %s, carga incorrecta\!
GroupManager.DISABLED=¡La versión %s está deshabilitada\!
GroupManager.ENABLED=¡La versión %s está habilitada\!
GroupManager.ERROR_LOADING=Ocurrió un error al cargar GroupManager
GroupManager.ERROR_SCHEDULING_SUPERPERMS=No se pudo programar la actualización de superperms.
GroupManager.FILE_CORRUPT=El siguiente archivo está corrupto: %s
GroupManager.PERMISSION_DIRECT_ACCESS=El %s ya tiene acceso directo a ese permiso.
GroupManager.PERMISSION_DIRECT_ACCESS_ALREADY=El %s ya tiene acceso directo a ese permiso.
GroupManager.PERMISSION_EXCEPTION=El %s ya tiene una excepción para este nodo.
GroupManager.PERMISSION_EXCEPTION_ALREADY=El %s ya tiene una excepción para este nodo.
GroupManager.PERMISSION_MATCHING_NEGATION=El %s ya tiene un nodo negado coincidente.
GroupManager.PERMISSION_MATCHING_NEGATION_ALREADY=El %s ya tiene un nodo negado coincidente.
GroupManager.PERMISSION_NODE=Nodo:
GroupManager.REFRESHED=Archivos de datos actualizados.
GroupManager.SCHEDULED_DATA_SAVING_DISABLED=¡El guardado de datos programado está deshabilitado\!
GroupManager.SCHEDULED_DATA_SAVING_SET=¡El guardado de datos programado se establece cada %d minutos\!

# Tasks
BukkitPermsUpdateTask.BUKKIT_PERMISSIONS_UPDATED=¡Permisos de Bukkit actualizados\!
UpdateTask.ERROR_PARSING_VERSION=Hubo un problema al analizar la cadena de versión.
UpdateTask.ERROR_VERSION_CHECKING=Hubo un problema al intentar comprobar la última versión.
UpdateTask.UPDATE_AVAILABLE=¡La versión estable: %s está disponible\! Aún estás ejecutando la versión: %s
UpdateTask.WE_ARE_UP_TO_DATE=No hay una nueva versión disponible

# GMWorldListener
GMWorldListener.CONFIGURE_NEW_WORLD=No olvides configurar/espejar este mundo en config.yml.
GMWorldListener.CREATING_DATA=Creando datos para:
GMWorldListener.DETECTED_NEW_WORLD=Nuevo mundo detectado...
GMWorldListener.ERROR_UNRECOGNISED_WORLD=No se pudo configurar este mundo.

# Command Syntax
MANCHECKW_SYNTAX=\ (/mancheckw <world>)
MANDEMOTE_SYNTAX=\ (/mandemote <user> <group>)
MANGADD_SYNTAX=\ (/mangadd <group>)
MANGADDI_SYNTAX=\ (/mangaddi <group1> <group2>)
MANGADDP_SYNTAX=\ (/mangaddp <group> <permission>[|1d1h1m] [permission2] [permission3]...)
MANGADDV_SYNTAX=\ (/mangaddv <group> <variable> <value>)
MANGCHECKP_SYNTAX=\ (/mangcheckp <group> <permission>)
MANGCHECKV_SYNTAX=\ (/mangcheckv <group> <variable>)
MANGCLEARP_SYNTAX=\ (/mangclearp <group>)
MANGDELP_SYNTAX=\ (/mangdelp <user> <permission> [permission2] [permission3]...)
MANGDELV_SYNTAX=\ (/mangdelv <group> <variable>)
MANGDEL_SYNTAX=\ (/mangdelv <group>)
MANGDELI_SYNTAX=\ (/mangdeli <group1> <group2>)
MANGLISTP_SYNTAX=\ (/manglistp <group>)
MANGLISTV_SYNTAX=\ (/manglistv <group>)
MANPROMOTE_SYNTAX=\ (/manpromote <user> <group>)
MANSELECT_SYNTAX=\ (/manselect <world>)
MANUADD_SYNTAX=\ (/manuadd <user> <group> | optional [world])
MANUADDP_SYNTAX=\ (/manuaddp <user> <permission>[|1d1h1m] [permission2] [permission3]...)
MANUADDSUB_SYNTAX=\ (/manuaddsub <user> <group>[|1d1h1m] [group2] [group3]...)
MANUADDV_SYNTAX=\ (/manuaddv <user> <variable> <value>)
MANUCHECKP_SYNTAX=\ (/manucheckp <user> <permission>)
MANUCHECKV_SYNTAX=\ (/manucheckv <user> <variable>)
MANUCLEARP_SYNTAX=\ (/manuclearp <user>)
MANUDEL_SYNTAX=\ (/manudel <user>)
MANUDELP_SYNTAX=\ (/manudelp <user> <permission> [permission2] [permission3]...)
MANUDELSUB_SYNTAX=\ (/manudelsub <user> <group>)
MANUDELV_SYNTAX=\ (/manudelv <user> <variable>)
MANULISTP_SYNTAX=\ (/manulistp <user> [+])
MANULISTV_SYNTAX=\ (/manUlistv <user>)
MANWHOIS_SYNTAX=\ (/manwhois <user>)
MANUADDTEMP_SYNTAX=\ (/manuaddtemp <player>)
MANUDELTEMP_SYNTAX=\ (/manudeltemp <player>)
